services:
    netbull_auth.security.forced_logout_listener:
        class: NetBull\AuthBundle\EventListener\ForcedLogoutListener
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@request_stack'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - ''
            - ''
            - ''
        tags:
            -   name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
                priority: 0
